version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./quoridor:/usr/quoridor
    user: "${UID}:${GID}"
    command: bash -c "cargo build && cargo run"
    working_dir: /usr/quoridor
    ports:
      - "8383"
