version: "3"

services:
  api:
    image: rust
    volumes:
      - ./src:/usr/src
    command: bash -c "cargo install --path . && cargo build && cargo run"
    working_dir: /usr/src
    ports:
      - "8383"
