version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./quoridor:/usr/quoridor
    command: bash -c "cargo install --path . && cargo build && cargo run"
    working_dir: /usr/quoridor
    ports:
      - "8383"
