[package]
name = "quoridor"
version = "0.1.0"
edition = '2018'

[dependencies]
actix-web = "3"
serde = { version = "1", features = ["derive"] }
env_logger = "0.7"
diesel = { version = "1.4.4", features = ["postgres"] }

[dev-dependencies]
actix-rt = "1"
